export type PlanEntitlements = Record<string, boolean | number>;

export const PLAN_ENTITLEMENT_KEYS = {
  PATIENTS_ACTIVE_LIMIT: 'patients.active.limit',
  PATIENTS_TOTAL_LIMIT: 'patients.total.limit',
  PATIENTS_EDIT_ACCESS: 'patients.edit.access',
  PLANS_EDIT_ACCESS: 'plans.edit.access',
  CONSULTATIONS_MONTHLY_LIMIT: 'consultations.monthly.limit',
  CONSULTATIONS_SAVED_LIMIT: 'consultations.saved.limit',
  PDF_MONTHLY_LIMIT: 'pdf.monthly.limit',
  PDF_EXPORTS_TOTAL_LIMIT: 'pdf.exports.total.limit',
  FOLLOWUPS_PRIVATE_ACTIVE_LIMIT: 'followups.private.active.limit',
  INGREDIENTS_BASE_READ: 'ingredients.base.read',
  CLINICAL_CALCULATOR_ACCESS: 'clinical_calculator.access',
  CLINICAL_CALCULATOR_LIMIT: 'clinical_calculator.limit',
  FOOD_GROUPS_ACCESS: 'food_groups.access',
  FOOD_GROUPS_TOTAL_LIMIT: 'food_groups.total.limit',
  AI_CALLS_LIMIT: 'ai.calls.limit',
  AI_OPERATIONS_TOTAL_LIMIT: 'ai.operations.total.limit',
  AI_AUTOFILL_ACCESS: 'ai.autofill.access',
  APPOINTMENTS_ACCESS: 'appointments.access',
  GOOGLE_CALENDAR_SYNC: 'google_calendar.sync',
  NUTRITIONIST_PORTAL_ACCESS: 'nutritionist_portal.access',
  SII_INVOICES_ACCESS: 'sii_invoices.access',
  CREATIONS_SAVE_LIMIT: 'creations.save.limit',
  CREATIONS_EDIT_ACCESS: 'creations.edit.access',
  CREATIONS_IMPORT_ACCESS: 'creations.import.access',
  CLINICAL_RESTRICTIONS_CREATE_ACCESS: 'clinical_restrictions.create.access',
  METRICS_CREATE_ACCESS: 'metrics.create.access',
  CLINICAL_CALCULATOR_USE_ACCESS: 'clinical_calculator.use.access',
} as const;

export const MEMBERSHIP_PLAN_ENTITLEMENTS: Record<string, PlanEntitlements> = {
  free: {
    [PLAN_ENTITLEMENT_KEYS.PATIENTS_ACTIVE_LIMIT]: 4,
    [PLAN_ENTITLEMENT_KEYS.PATIENTS_TOTAL_LIMIT]: 4,
    [PLAN_ENTITLEMENT_KEYS.PATIENTS_EDIT_ACCESS]: false,
    [PLAN_ENTITLEMENT_KEYS.PLANS_EDIT_ACCESS]: false,
    [PLAN_ENTITLEMENT_KEYS.CONSULTATIONS_MONTHLY_LIMIT]: 3,
    [PLAN_ENTITLEMENT_KEYS.CONSULTATIONS_SAVED_LIMIT]: 3,
    [PLAN_ENTITLEMENT_KEYS.PDF_MONTHLY_LIMIT]: 3,
    [PLAN_ENTITLEMENT_KEYS.PDF_EXPORTS_TOTAL_LIMIT]: 3,
    [PLAN_ENTITLEMENT_KEYS.FOLLOWUPS_PRIVATE_ACTIVE_LIMIT]: 6,
    [PLAN_ENTITLEMENT_KEYS.INGREDIENTS_BASE_READ]: true,
    [PLAN_ENTITLEMENT_KEYS.CLINICAL_CALCULATOR_ACCESS]: true,
    [PLAN_ENTITLEMENT_KEYS.CLINICAL_CALCULATOR_USE_ACCESS]: false,
    [PLAN_ENTITLEMENT_KEYS.CLINICAL_CALCULATOR_LIMIT]: 0,
    [PLAN_ENTITLEMENT_KEYS.FOOD_GROUPS_ACCESS]: true,
    [PLAN_ENTITLEMENT_KEYS.FOOD_GROUPS_TOTAL_LIMIT]: 1,
    [PLAN_ENTITLEMENT_KEYS.AI_CALLS_LIMIT]: 4,
    [PLAN_ENTITLEMENT_KEYS.AI_OPERATIONS_TOTAL_LIMIT]: 4,
    [PLAN_ENTITLEMENT_KEYS.AI_AUTOFILL_ACCESS]: true,
    [PLAN_ENTITLEMENT_KEYS.APPOINTMENTS_ACCESS]: false,
    [PLAN_ENTITLEMENT_KEYS.GOOGLE_CALENDAR_SYNC]: false,
    [PLAN_ENTITLEMENT_KEYS.NUTRITIONIST_PORTAL_ACCESS]: false,
    [PLAN_ENTITLEMENT_KEYS.SII_INVOICES_ACCESS]: false,
    [PLAN_ENTITLEMENT_KEYS.CREATIONS_SAVE_LIMIT]: 3,
    [PLAN_ENTITLEMENT_KEYS.CREATIONS_EDIT_ACCESS]: false,
    [PLAN_ENTITLEMENT_KEYS.CREATIONS_IMPORT_ACCESS]: false,
    [PLAN_ENTITLEMENT_KEYS.CLINICAL_RESTRICTIONS_CREATE_ACCESS]: false,
    [PLAN_ENTITLEMENT_KEYS.METRICS_CREATE_ACCESS]: false,
  },
  iniciante: {
    [PLAN_ENTITLEMENT_KEYS.PATIENTS_ACTIVE_LIMIT]: -1,
    [PLAN_ENTITLEMENT_KEYS.PATIENTS_TOTAL_LIMIT]: -1,
    [PLAN_ENTITLEMENT_KEYS.PATIENTS_EDIT_ACCESS]: true,
    [PLAN_ENTITLEMENT_KEYS.PLANS_EDIT_ACCESS]: true,
    [PLAN_ENTITLEMENT_KEYS.CONSULTATIONS_MONTHLY_LIMIT]: -1,
    [PLAN_ENTITLEMENT_KEYS.CONSULTATIONS_SAVED_LIMIT]: -1,
    [PLAN_ENTITLEMENT_KEYS.PDF_MONTHLY_LIMIT]: -1,
    [PLAN_ENTITLEMENT_KEYS.PDF_EXPORTS_TOTAL_LIMIT]: -1,
    [PLAN_ENTITLEMENT_KEYS.FOLLOWUPS_PRIVATE_ACTIVE_LIMIT]: -1,
    [PLAN_ENTITLEMENT_KEYS.INGREDIENTS_BASE_READ]: true,
    [PLAN_ENTITLEMENT_KEYS.CLINICAL_CALCULATOR_ACCESS]: true,
    [PLAN_ENTITLEMENT_KEYS.CLINICAL_CALCULATOR_USE_ACCESS]: true,
    [PLAN_ENTITLEMENT_KEYS.CLINICAL_CALCULATOR_LIMIT]: -1,
    [PLAN_ENTITLEMENT_KEYS.FOOD_GROUPS_ACCESS]: true,
    [PLAN_ENTITLEMENT_KEYS.FOOD_GROUPS_TOTAL_LIMIT]: -1,
    [PLAN_ENTITLEMENT_KEYS.AI_CALLS_LIMIT]: -1,
    [PLAN_ENTITLEMENT_KEYS.AI_OPERATIONS_TOTAL_LIMIT]: -1,
    [PLAN_ENTITLEMENT_KEYS.AI_AUTOFILL_ACCESS]: true,
    [PLAN_ENTITLEMENT_KEYS.APPOINTMENTS_ACCESS]: true,
    [PLAN_ENTITLEMENT_KEYS.GOOGLE_CALENDAR_SYNC]: true,
    [PLAN_ENTITLEMENT_KEYS.NUTRITIONIST_PORTAL_ACCESS]: true,
    [PLAN_ENTITLEMENT_KEYS.SII_INVOICES_ACCESS]: true,
    [PLAN_ENTITLEMENT_KEYS.CREATIONS_SAVE_LIMIT]: -1,
    [PLAN_ENTITLEMENT_KEYS.CREATIONS_EDIT_ACCESS]: true,
    [PLAN_ENTITLEMENT_KEYS.CREATIONS_IMPORT_ACCESS]: true,
    [PLAN_ENTITLEMENT_KEYS.CLINICAL_RESTRICTIONS_CREATE_ACCESS]: true,
    [PLAN_ENTITLEMENT_KEYS.METRICS_CREATE_ACCESS]: true,
  },
  pro: {
    [PLAN_ENTITLEMENT_KEYS.PATIENTS_ACTIVE_LIMIT]: -1,
    [PLAN_ENTITLEMENT_KEYS.PATIENTS_TOTAL_LIMIT]: -1,
    [PLAN_ENTITLEMENT_KEYS.PATIENTS_EDIT_ACCESS]: true,
    [PLAN_ENTITLEMENT_KEYS.PLANS_EDIT_ACCESS]: true,
    [PLAN_ENTITLEMENT_KEYS.CONSULTATIONS_MONTHLY_LIMIT]: -1,
    [PLAN_ENTITLEMENT_KEYS.CONSULTATIONS_SAVED_LIMIT]: -1,
    [PLAN_ENTITLEMENT_KEYS.PDF_MONTHLY_LIMIT]: -1,
    [PLAN_ENTITLEMENT_KEYS.PDF_EXPORTS_TOTAL_LIMIT]: -1,
    [PLAN_ENTITLEMENT_KEYS.FOLLOWUPS_PRIVATE_ACTIVE_LIMIT]: -1,
    [PLAN_ENTITLEMENT_KEYS.INGREDIENTS_BASE_READ]: true,
    [PLAN_ENTITLEMENT_KEYS.CLINICAL_CALCULATOR_ACCESS]: true,
    [PLAN_ENTITLEMENT_KEYS.CLINICAL_CALCULATOR_USE_ACCESS]: true,
    [PLAN_ENTITLEMENT_KEYS.CLINICAL_CALCULATOR_LIMIT]: -1,
    [PLAN_ENTITLEMENT_KEYS.FOOD_GROUPS_ACCESS]: true,
    [PLAN_ENTITLEMENT_KEYS.FOOD_GROUPS_TOTAL_LIMIT]: -1,
    [PLAN_ENTITLEMENT_KEYS.AI_CALLS_LIMIT]: -1,
    [PLAN_ENTITLEMENT_KEYS.AI_OPERATIONS_TOTAL_LIMIT]: -1,
    [PLAN_ENTITLEMENT_KEYS.AI_AUTOFILL_ACCESS]: true,
    [PLAN_ENTITLEMENT_KEYS.APPOINTMENTS_ACCESS]: true,
    [PLAN_ENTITLEMENT_KEYS.GOOGLE_CALENDAR_SYNC]: true,
    [PLAN_ENTITLEMENT_KEYS.NUTRITIONIST_PORTAL_ACCESS]: true,
    [PLAN_ENTITLEMENT_KEYS.SII_INVOICES_ACCESS]: true,
    [PLAN_ENTITLEMENT_KEYS.CREATIONS_SAVE_LIMIT]: -1,
    [PLAN_ENTITLEMENT_KEYS.CREATIONS_EDIT_ACCESS]: true,
    [PLAN_ENTITLEMENT_KEYS.CREATIONS_IMPORT_ACCESS]: true,
    [PLAN_ENTITLEMENT_KEYS.CLINICAL_RESTRICTIONS_CREATE_ACCESS]: true,
    [PLAN_ENTITLEMENT_KEYS.METRICS_CREATE_ACCESS]: true,
  },
  plus: {
    [PLAN_ENTITLEMENT_KEYS.PATIENTS_ACTIVE_LIMIT]: -1,
    [PLAN_ENTITLEMENT_KEYS.PATIENTS_TOTAL_LIMIT]: -1,
    [PLAN_ENTITLEMENT_KEYS.PATIENTS_EDIT_ACCESS]: true,
    [PLAN_ENTITLEMENT_KEYS.PLANS_EDIT_ACCESS]: true,
    [PLAN_ENTITLEMENT_KEYS.CONSULTATIONS_MONTHLY_LIMIT]: -1,
    [PLAN_ENTITLEMENT_KEYS.CONSULTATIONS_SAVED_LIMIT]: -1,
    [PLAN_ENTITLEMENT_KEYS.PDF_MONTHLY_LIMIT]: -1,
    [PLAN_ENTITLEMENT_KEYS.PDF_EXPORTS_TOTAL_LIMIT]: -1,
    [PLAN_ENTITLEMENT_KEYS.FOLLOWUPS_PRIVATE_ACTIVE_LIMIT]: -1,
    [PLAN_ENTITLEMENT_KEYS.INGREDIENTS_BASE_READ]: true,
    [PLAN_ENTITLEMENT_KEYS.CLINICAL_CALCULATOR_ACCESS]: true,
    [PLAN_ENTITLEMENT_KEYS.CLINICAL_CALCULATOR_USE_ACCESS]: true,
    [PLAN_ENTITLEMENT_KEYS.CLINICAL_CALCULATOR_LIMIT]: -1,
    [PLAN_ENTITLEMENT_KEYS.FOOD_GROUPS_ACCESS]: true,
    [PLAN_ENTITLEMENT_KEYS.FOOD_GROUPS_TOTAL_LIMIT]: -1,
    [PLAN_ENTITLEMENT_KEYS.AI_CALLS_LIMIT]: -1,
    [PLAN_ENTITLEMENT_KEYS.AI_OPERATIONS_TOTAL_LIMIT]: -1,
    [PLAN_ENTITLEMENT_KEYS.AI_AUTOFILL_ACCESS]: true,
    [PLAN_ENTITLEMENT_KEYS.APPOINTMENTS_ACCESS]: true,
    [PLAN_ENTITLEMENT_KEYS.GOOGLE_CALENDAR_SYNC]: true,
    [PLAN_ENTITLEMENT_KEYS.NUTRITIONIST_PORTAL_ACCESS]: true,
    [PLAN_ENTITLEMENT_KEYS.SII_INVOICES_ACCESS]: true,
    [PLAN_ENTITLEMENT_KEYS.CREATIONS_SAVE_LIMIT]: -1,
    [PLAN_ENTITLEMENT_KEYS.CREATIONS_EDIT_ACCESS]: true,
    [PLAN_ENTITLEMENT_KEYS.CREATIONS_IMPORT_ACCESS]: true,
    [PLAN_ENTITLEMENT_KEYS.CLINICAL_RESTRICTIONS_CREATE_ACCESS]: true,
    [PLAN_ENTITLEMENT_KEYS.METRICS_CREATE_ACCESS]: true,
  },
};

export const getMembershipPlanEntitlements = (slug: string) =>
  MEMBERSHIP_PLAN_ENTITLEMENTS[slug.toLowerCase()] || {};

export const normalizeMembershipPlanKey = (value: string) => {
  const normalized = value.trim().toLowerCase();

  if (normalized.includes('free') || normalized.includes('gratis') || normalized.includes('freemium'))
    return 'free';
  if (normalized.includes('iniciante') || normalized.includes('starter'))
    return 'iniciante';
  if (
    normalized.includes('pro') ||
    normalized.includes('premium') ||
    normalized.includes('plus') ||
    normalized.includes('enterprise')
  )
    return 'pro';

  return normalized;
};

export const getMembershipPlanKey = (plan: {
  name?: string | null;
  slug?: string | null;
}) => normalizeMembershipPlanKey(plan.slug || plan.name || '');

export const getMembershipPlanEntitlementsFromPlan = (plan: {
  name?: string | null;
  slug?: string | null;
}) => MEMBERSHIP_PLAN_ENTITLEMENTS[getMembershipPlanKey(plan)] || {};
