import { Patient } from "./types";

export const MOCK_PATIENTS: Patient[] = [
  {
    id: "1",
    nutritionistId: "nutri-1",
    fullName: "Ana Silva",
    email: "ana.silva@email.com",
    birthDate: "1990-05-15",
    gender: "F",
    status: "Active",
    lastVisit: "2023-11-01",
    weight: 65.5,
    height: 165,
    dietRestrictions: ["Vegetariana", "Intolerante Lactosa"],
    nutritionalFocus: "Déficit Calórico",
    clinicalSummary: "Paciente reporta buena adherencia. Energía recuperada.",
    fitnessGoals: "Mejorar perfil lipídico",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "2",
    nutritionistId: "nutri-1",
    fullName: "Carlos Ruiz",
    email: "carlos.ruiz@email.com",
    birthDate: "1985-08-20",
    gender: "M",
    status: "Inactive",
    lastVisit: "2023-09-12",
    weight: 85.0,
    height: 178,
    dietRestrictions: ["Celíaco"],
    nutritionalFocus: "Hipertrofia",
    clinicalSummary: "",
    fitnessGoals: "Ganar 3kg de músculo",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "3",
    nutritionistId: "nutri-1",
    fullName: "Maria Gonzalez",
    email: "maria.gonzalez@email.com",
    birthDate: "1992-02-28",
    gender: "F",
    status: "Active",
    lastVisit: "2023-10-30",
    weight: 58.2,
    height: 160,
    dietRestrictions: ["Alergia Marisco"],
    nutritionalFocus: "Mantenimiento",
    clinicalSummary: "Problemas de saciedad en las tardes.",
    fitnessGoals: "Mejorar resistencia",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
